### ISSUE TITLE
开启的时候报错

### ISSUE THREAD

**Issue by wo642436249** [Reasno/fastmongo#1]
执行 php bin/hyperf.php vendor:publish reasno/fastmongo时候报/hyperf-project/config/autoload/mongodb.php] already exists错误

**Comment by Reasno** [comment]
已经存在就不会再执行 这是hyperf/devtool的逻辑

**Comment by Reasno** [comment]
如果要覆盖要加-f

**Comment by wo642436249** [comment]
那意思就是这个命令只执行一次就可以了，接下来直接php hyperf.php start就可以了吧



---原始邮件---
发件人: "谷溪"<notifications@github.com&gt;
发送时间: 2020年6月2日(周二) 下午3:11
收件人: "Reasno/fastmongo"<fastmongo@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wo642436249"<642436249@qq.com&gt;;
主题: Re: [Reasno/fastmongo] 开启的时候报错 (#1)




 
如果要覆盖要加-f

**Comment by Reasno** [comment]
> p hyperf.

是的。

**Comment by wo642436249** [comment]
好的



---原始邮件---
发件人: "谷溪"<notifications@github.com&gt;
发送时间: 2020年6月2日(周二) 下午3:23
收件人: "Reasno/fastmongo"<fastmongo@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"wo642436249"<642436249@qq.com&gt;;
主题: Re: [Reasno/fastmongo] 开启的时候报错 (#1)




  
p hyperf.
  
是的。
