### ISSUE TITLE
failed, Error: Exec format error[8]

### ISSUE THREAD

**Issue by jian-D** [Reasno/fastmongo#10]
Warning: Swoole\Process::exec(): execv(/bhshejiao/vendor/bin/mongo-proxy-linux-amd64) failed, Error: Exec format error[8] in /bhshejiao/vendor/hyperf/gotask/src/Process/GoTaskProcess.php on line 65

**Comment by Reasno** [comment]
什么系统？你可能需要自己编译go代码。

**Comment by Reasno** [comment]
chmod +x

**Comment by jian-D** [comment]
也许不是chmod + x 的问题？
权限已经有了：
-rwxr-xr-x. 1 root root 1067 Jan 27 17:00 mongo-proxy-darwin-amd64
-rwxr-xr-x. 1 root root 1067 Jan 27 18:41 mongo-proxy-linux-amd64
还是报同样的错

**Comment by Reasno** [comment]
贴下系统版本，另外 直接 ./mongo-proxy-linux-amd64 试试。

**Comment by jian-D** [comment]
# cat /proc/version
Linux version 3.10.0-327.28.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Aug 18 19:05:49 UTC 2016

**Comment by Reasno** [comment]
那应该是arch不是amd64，需要自行编译呢。。

**Comment by jian-D** [comment]
不懂就问，什么意思？

**Comment by Reasno** [comment]
> 不懂就问，什么意思？

先试试重新安装吧。

**Comment by jian-D** [comment]
重装系统？

**Comment by jian-D** [comment]
在linux装的docker
# docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eXXX
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03faXXX
 docker-init:
  Version:          0.18.0
  GitCommit:        fecXXX

**Comment by jian-D** [comment]
[root@f8c1cc8db04a bin]# ./mongo-proxy-linux-amd64 
./mongo-proxy-linux-amd64: line 1: XSym: command not found
./mongo-proxy-linux-amd64: line 2: 0047: command not found
./mongo-proxy-linux-amd64: line 3: d6a1dd08b3408a2872900beac52ec344: command not found

**Comment by jian-D** [comment]
vendor/reasno/fastmongo/src/DomainConfig.php文件里的getExecutable()
我直接改掉，访问包里的文件就可以：
public function getExecutable(): string
    {
        /*if ($this->isMac()) {
            return BASE_PATH . '/vendor/bin/mongo-proxy-darwin-amd64';
        }
        return BASE_PATH . '/vendor/bin/mongo-proxy-linux-amd64';*/
        if ($this->isMac()) {
            return BASE_PATH . '/vendor/bin/mongo-proxy-darwin-amd64';
        }
        return BASE_PATH . '/vendor/bin/mongo-proxy-linux-amd64';
    }

**Comment by Reasno** [comment]
没看懂 改了哪了

**Comment by jian-D** [comment]
mongo-proxy-linux-amd64 的路径直接指向扩展包里的文件

**Comment by Reasno** [comment]
> mongo-proxy-linux-amd64 的路径直接指向扩展包里的文件路径

哦哦 那应该是composer安装的时候的问题 因为composer应该把文件移动过去的
