### ISSUE TITLE
依照文档中的安装 无法启动

### ISSUE THREAD

**Issue by 411906015** [Reasno/fastmongo#18]
![image](https://user-images.githubusercontent.com/35674916/161222115-827eda12-3752-4f36-84bc-47213037c1db.png)

已安装gotask，配置如下
![image](https://user-images.githubusercontent.com/35674916/161222223-8562817c-a196-431c-9f38-41c6cc746ffc.png)
![image](https://user-images.githubusercontent.com/35674916/161222267-fc2d566d-d812-4015-b067-cd9ecb6ad424.png)

已安装当前组件，配置如下
![image](https://user-images.githubusercontent.com/35674916/161222423-2875b5ee-a193-4935-a42b-41ba9d055705.png)

执行代码：
![image](https://user-images.githubusercontent.com/35674916/161222488-61f08faa-1e0f-4cb6-bb72-9114ba733f55.png)

就会发生报错

**Comment by 411906015** [comment]
抱歉，我是瓜皮，我不应该安装gotask，只需要安装本组件就可以了

**Comment by diaojinlong** [comment]
composer require reasno/fastmongo 默认安装的是v0.1.1和你的报错一样，最后我升级到v0.2.6就解决了。
