### ISSUE TITLE
missing .sock when use Hyperf command

### ISSUE THREAD

**Issue by alert2joe** [Reasno/fastmongo#2]
在Controller 中 MongoClient 正常使用.

但在 Hyperf Command 中. 就發生錯誤,

我已經使用一個全新的Hyperf 2.0去測試這問題, ,

發現每當運行 php bin/hyperf.php start 時.. 都會在/tmp /中建立一個 {app name}_{XXXX}.sock 的file .

但運行Hyperf Command時,  tmp /中 並沒有新增相關的sock file. 而出現以下錯誤.

`[WARNING] RemoteGoTask::__call failed, because unable to establish connection unix:///tmp/skeleton_5f363719a4f47.sock
PHP Fatal error:  Uncaught Spiral\Goridge\Exceptions\RelayException: No such file or directory (2) in /hyperf-skeleton/vendor/hyperf/gotask/src/Relay/CoroutineSocketRelay.php:134`

以下是composer.json

`    "require": {
        "php": ">=7.2",
        "ext-swoole": ">=4.5",
        "hyperf/cache": "~2.0.0",
        "hyperf/command": "^2.0",
        "hyperf/config": "~2.0.0",
        "hyperf/db-connection": "~2.0.0",
        "hyperf/framework": "~2.0.0",
        "hyperf/guzzle": "~2.0.0",
        "hyperf/http-server": "~2.0.0",
        "hyperf/logger": "~2.0.0",
        "hyperf/memory": "~2.0.0",
        "hyperf/process": "~2.0.0",
        "hyperf/redis": "~2.0.0",
        "hyperf/async-queue": "~2.0.0",
        "reasno/fastmongo": "^0.2.1"
    },`

**Comment by Reasno** [comment]
![image](https://user-images.githubusercontent.com/3881629/90231160-5057c980-de4d-11ea-8fc7-177cc608cb1d.png)
command需要实现一下WithGoTask 接口。默认command是不启动gotask基础设施的。
