### ISSUE TITLE
文件权限问题

### ISSUE THREAD

**Issue by Kay-iu** [Reasno/fastmongo#5]
PHP Warning:  Swoole\Process::exec(): execv(/data/wwwroot/xx/vendor/bin/mongo-proxy-linux-amd64) failed, Error: Permission denied[13] in /data/wwwroot/xxx/vendor/hyperf/gotask/src/Process/GoTaskProcess.php on line 65
在使用fastmongo的时候报这个错，麻烦告知下错误
![1](https://user-images.githubusercontent.com/76156222/103475434-082f4880-4de8-11eb-8bfa-183239c0678e.png)
![2](https://user-images.githubusercontent.com/76156222/103475437-0b2a3900-4de8-11eb-84bc-fcb366b0e275.png)

**Comment by Reasno** [comment]
给下这个目录的执行权限
