### ISSUE TITLE
Hyperf中启动服务后，该组件是不是会输出空信息？

### ISSUE THREAD

**Issue by wulianggit** [Reasno/fastmongo#8]
![image](https://user-images.githubusercontent.com/19743805/105842242-db4e0a00-6010-11eb-834f-fec8bfe9af2b.png)
[INFO] Worker#0 started.
[INFO] HTTP Server listening at 0.0.0.0:9501
[INFO] Process[queue.default.0] start.
[INFO] Process[gotask.0] start.
[INFO] Worker#1 started.
[INFO]
[INFO]
[INFO]
[INFO]
[INFO]
[INFO]
[INFO]
[INFO]
[INFO]
[INFO]

> 一直在定时输出

**Comment by Reasno** [comment]
应该不是 印象中没有用过stdoutlogger

**Comment by wulianggit** [comment]
> 应该不是 印象中没有用过stdoutlogger

> 我也没找到，但是把这个包移除后，就正常了。很诡异

**Comment by jian-D** [comment]
我也是一直这样

**Comment by wulianggit** [comment]
> 我也是一直这样

你找到原因了吗？

**Comment by jian-D** [comment]
> > 我也是一直这样
> 
> 你找到原因了吗？

我也还没找到

**Comment by wc1217** [comment]
在 Hyperf\GoTask\Listener\LogRedirectListener
第74行`$this->logOutput((string) $recv);` 
$recv===false, 转成string后就是空
