### ISSUE TITLE
Return value of Hyperf\GoTask\MongoClient\Collection::makePayload() must be of the type string, null returned

### ISSUE THREAD

**Issue by jian-D** [Reasno/fastmongo#9]
![image](https://user-images.githubusercontent.com/25168801/105955389-2ae41280-60b1-11eb-880d-0560acdccb5b.png)

**Comment by jian-D** [comment]
报错信息
string(9) "TypeError"
string(109) "Return value of Hyperf\GoTask\MongoClient\Collection::makePayload() must be of the type string, null returned"
string(62) "/bhshejiao/vendor/hyperf/gotask/src/MongoClient/Collection.php"

**Comment by Reasno** [comment]
see #10
